### ISSUE TITLE
C with hachek is wrongly depicted with a breve

### ISSUE THREAD

**Issue by merni-ns** [zephyris/openttd-ttf#1]
![image](https://github.com/zephyris/openttd-ttf/assets/66267867/5caf02dc-f5d5-4822-ae35-501db6c5e4e4)
(Screenshot stolen from peter1138)

In Czech as well as various other Slavic languages written in Latin script, the letter [C with caron/háček](https://en.wikipedia.org/wiki/%C4%8C) is used. This should look like Čč.

Whereas, in this font, what is implemented is C with [breve](https://en.wikipedia.org/wiki/Breve) (c + ◌̆). This does not seem to be actually used in any major language.

Please replace this "C with breve" with "C with caron".

**Comment by zephyris** [comment]
Fixed in 6f406b0
