### ISSUE TITLE
OpenTTD-Sans doesn't get rendered if seleceted as a GUI font for KDE

### ISSUE THREAD

**Issue by MrDowntempo** [zephyris/openttd-ttf#4]
I thought it would be lovely to use OpenTTD-Sans as the titlebar font on my PC's Desktop Titlebars to give it the same look as the game. I've installed the font, and verified it works in places like LibreOffice. And when (I'm using KDE Plasma) I browse which fonts I can use in the interface, OpenTTD-Sans is there in the list, and renders in that list correctly. But when I actually select it, it isn't used. This isn't an issue with any other font in the list. I'm not sure what is preventing it from being used. Perhaps it is that its only available in Bold and not Regular? Perhaps its missing glyphs? (FontForge through up a bunch of errors I didn't fully understand when I was investigating the font) In any case, it would be great if that could be fixed up so my desktop could further resemble OpenTTD.

**Comment by MrDowntempo** [comment]
So uh... its working now. After a couple reboots the font started working in my title bar. I guess that's soemthing on my end. Still strange as hell that no other font of mine required a reboot, even other fonts installed the same way (in .local/share/fonts). So I'm going to mark this as solved, but still might be worth investigating if others have a similar issue.

**Comment by LaPingvino** [comment]
I usually run fc-cache -v after adding any new font, and that should normally take care of it immediately. Seeing it works now I suspect it was just a font cache issue.

**Comment by zephyris** [comment]
Great, I'm glad you've got it working.
